##############activemq#########
spring:
  activemq:
    broker-url: tcp://192.168.26.128:61616
#    in-memory: true
#    pool:
#      enabled: false
#  jms:
#    pub-sub-domain: true
  redis:
    host: 192.168.26.128
    port: 6379
    password: root
##############################


##########数据库###############
  datasource:
    url: jdbc:mysql://192.168.26.128:3306/test
    username: root
    password: root
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
#########################


##########log#############
logging:
  level: debug
  path: d:/springbootlog/logs/
###########################

#############tomcat########
server:
  port: 80 #端口
  context-path: / #部署路径
  session:
    timeout: 60000
management:
  security:
    enabled: false
###########################

